class ZCL_IM_WORKORDER_UPDATE definition
  public
  final
  create public .

public section.

  interfaces IF_BADI_INTERFACE .
  interfaces IF_EX_WORKORDER_UPDATE .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IM_WORKORDER_UPDATE IMPLEMENTATION.


  method IF_EX_WORKORDER_UPDATE~ARCHIVE_OBJECTS.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~AT_DELETION_FROM_DATABASE.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~AT_RELEASE.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~AT_SAVE.
   DATA:GSWL_PRPS TYPE   PRPS.
   DATA:ERMSG  TYPE STRING .
   DATA: POSTWBS TYPE PS_POST1."WBS描述
   DATA: GS_ZCJ20N TYPE ZCJ20N_CHECK."CJ20N增强点检查开关
   "CJ20N、ZCJ20N保存网络号增强判断  added by IT02 151020 begin
   IF  ( SY-TCODE =  'CJ20N'  OR SY-TCODE =  'ZCJ20N' ) AND IS_HEADER_DIALOG-BUKRS = '1800'. "判断在CJ20N且公司代码为1800
     SELECT SINGLE * INTO GS_ZCJ20N FROM ZCJ20N_CHECK WHERE BUKRS = '1800' AND ZPSXMYS = '网络'.
      IF IS_HEADER_DIALOG-AUFNR+0(1) = '%' AND GS_ZCJ20N-ZON_OFF  EQ '1'.  "只有在ZCJ20N_CHECK维护表的相应 ZON_OFF为'1'才去执行
         ERMSG = IS_HEADER_DIALOG-AUFNR.
     "*WBS内码转换WBS元素
      CALL FUNCTION 'CONVERSION_EXIT_ABPSP_OUTPUT'
      EXPORTING
        INPUT  = IS_HEADER_DIALOG-PSPEL
      IMPORTING
        OUTPUT = POSTWBS.
     SELECT SINGLE * INTO GSWL_PRPS FROM PRPS WHERE POSID = POSTWBS.
      IF  GSWL_PRPS-STUFE NE '1'.
        CONCATENATE '该' IS_HEADER_DIALOG-AUFNR '网络未创建在首层WBS' INTO ERMSG .
        MESSAGE ERMSG TYPE 'E' .
      ENDIF.

      ENDIF.
    ENDIF.
    "CJ20N保存网络号增强判断  added by IT02 151020 end
  endmethod.


  METHOD IF_EX_WORKORDER_UPDATE~BEFORE_UPDATE.
  ENDMETHOD.


  method IF_EX_WORKORDER_UPDATE~CMTS_CHECK.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~INITIALIZE.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~IN_UPDATE.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~NUMBER_SWITCH.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~REORG_STATUS_ACTIVATE.
  endmethod.


  method IF_EX_WORKORDER_UPDATE~REORG_STATUS_ACT_CHECK.
  endmethod.


  METHOD IF_EX_WORKORDER_UPDATE~REORG_STATUS_REVOKE.
  ENDMETHOD.
ENDCLASS.
