REPORT ZCO005 .

PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G3 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G4 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G5 TYPE CHAR1 RADIOBUTTON GROUP G1.

"项目订单销售费用结转
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZCO005_1'.
ENDIF.

*项目订单成本发生明细
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZCO005_2'.
ENDIF.

*结转记录（可冲销）
IF G_G3 = 'X'.
  CALL TRANSACTION 'ZCO005_3'.
ENDIF.

*非合同项目/整改项目汇总表
IF G_G4 = 'X'.
  CALL TRANSACTION 'ZCO005_4'.
ENDIF.

*非合同项目/整改项目对应关系
IF G_G5 = 'X'.
  CALL TRANSACTION 'ZCO005_5'.
ENDIF.
