REPORT ZCO010.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G3 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G4 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G5 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G6 TYPE CHAR1 RADIOBUTTON GROUP G1.


"成本中心利润报表
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZCO010_1'.
ENDIF.

*销售类成本中心收入明细
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZCO010_2'.
ENDIF.

*生产类成本中心产值明细
IF G_G3 = 'X'.
  CALL TRANSACTION 'ZCO010_5'.
ENDIF.

*生产订单收货明细表
IF G_G4 = 'X'.
  CALL TRANSACTION 'ZCO010_3'.
ENDIF.

*生产订单投料明细表
IF G_G5 = 'X'.
  CALL TRANSACTION 'ZCO010_4'.
ENDIF.

*销售副总对应成本中心维护
IF G_G6 = 'X'.
  CALL TRANSACTION 'ZCO010_6'.
ENDIF.
