REPORT ZCO012.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G3 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G4 TYPE CHAR1 RADIOBUTTON GROUP G1.

"公司间采购成本收入计算
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZCO012_1'.
ENDIF.

*公司间采购报表
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZCO012_2'.
ENDIF.

*产品订单成本收入计算
IF G_G3 = 'X'.
  CALL TRANSACTION 'ZCO012_3'.
ENDIF.

*产品订单报表
IF G_G4 = 'X'.
  CALL TRANSACTION 'ZCO012_4'.
ENDIF.
