REPORT ZCO006.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G3 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G4 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G5 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G6 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G7 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G8 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G9 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G10 TYPE CHAR1 RADIOBUTTON GROUP G1.

"主营业务成本&收入报表
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZCO006_1'.
ENDIF.

*主营业务成本明细表
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZCO006_2'.
ENDIF.

*主营业务收入明细表
IF G_G3 = 'X'.
  CALL TRANSACTION 'ZCO006_3'.
ENDIF.

*工程成本明细表
IF G_G4 = 'X'.
  CALL TRANSACTION 'ZCO006_4'.
ENDIF.


*项目收款明细表更改为 应收&预收明细表
IF G_G5 = 'X'.
  CALL TRANSACTION 'ZCO006_5'.
ENDIF.

*产品标准成本明细表
IF G_G6 = 'X'.
  CALL TRANSACTION 'ZCO006_6'.
ENDIF.


*产品成本差异明细表
IF G_G7 = 'X'.
  CALL TRANSACTION 'ZCO006_7'.
ENDIF.

*工程费用明细表
IF G_G8 = 'X'.
  CALL TRANSACTION 'ZCO006_8'.
ENDIF.

*工程成本汇总表
IF G_G9 = 'X'.
  CALL TRANSACTION 'ZCO006_9'.
ENDIF.

*应收预收汇总
IF G_G10 = 'X'.
  CALL TRANSACTION 'ZCO006_10'.
ENDIF.
