FUNCTION ZFI_KOSTL.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     VALUE(P_BUKRS) TYPE  BUKRS OPTIONAL
*"  EXPORTING
*"     VALUE(R_MSG) TYPE  CHAR0256
*"  TABLES
*"      T_KOSTL STRUCTURE  ZKOSTL_INFO OPTIONAL
*"----------------------------------------------------------------------
DATA: T_CSKT LIKE TABLE OF CSKT WITH HEADER LINE.
DATA:GT_T001 LIKE TABLE OF T001 WITH HEADER LINE,
     GS_T001 LIKE T001 .
SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_T001
  FROM T001
  WHERE BUKRS = P_BUKRS.
SORT GT_T001 BY BUKRS.
SELECT BUKRS KOSTL  VERAK ERSDA
  INTO CORRESPONDING FIELDS OF TABLE T_KOSTL
  FROM CSKS
  WHERE  BUKRS = P_BUKRS .
  IF T_KOSTL[] IS NOT INITIAL.
   SELECT * INTO CORRESPONDING FIELDS OF TABLE T_CSKT
   FROM CSKT
  FOR ALL ENTRIES IN T_KOSTL
  WHERE KOKRS = '1000' AND KOSTL = T_KOSTL-KOSTL .
 SORT T_CSKT BY KOSTL.
LOOP AT T_KOSTL.
   READ TABLE GT_T001 INTO GS_T001 WITH KEY BUKRS = T_KOSTL-BUKRS BINARY SEARCH .
    IF SY-SUBRC = 0.
      T_KOSTL-BUTXT = GS_T001-BUTXT.
    ENDIF.
   READ TABLE T_CSKT WITH KEY KOSTL = T_KOSTL-KOSTL BINARY SEARCH.
    IF SY-SUBRC = 0.
       T_KOSTL-KTEXT = T_CSKT-KTEXT.
       MODIFY T_KOSTL.
      ENDIF.
  ENDLOOP.
   R_MSG = '据读取成功,请查看T_KOSTL表'.
 ELSE.
 R_MSG =  '数据读取失败,请重新更新检索条件' .
    ENDIF.
ENDFUNCTION.
