FUNCTION ZFI_NBDD.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  EXPORTING
*"     VALUE(R_MSG) TYPE  CHAR0256
*"  TABLES
*"      T_BUKRS STRUCTURE  ZBUKRS OPTIONAL
*"      T_AUART STRUCTURE  ZAUART OPTIONAL
*"      T_ZNBDD STRUCTURE  ZNBDD
*"----------------------------------------------------------------------
RANGES:P_BUKRS FOR COAS-BUKRS.
RANGES:P_AUART FOR COAS-AUART.
DATA:T_CSKT LIKE TABLE OF CSKT WITH HEADER LINE.
DATA:T_CSKT3 LIKE TABLE OF CSKT WITH HEADER LINE.

DATA:T_T003P like table of t003p with header line.
DATA:T_T001 LIKE TABLE OF T001 WITH HEADER LINE.
IF T_BUKRS[] IS NOT INITIAL.
   LOOP AT T_BUKRS.
       TRANSLATE T_BUKRS-BUKRS  TO UPPER CASE.
     P_BUKRS-SIGN = 'I'.
     P_BUKRS-OPTION = 'EQ'.
     P_BUKRS-LOW = T_BUKRS-BUKRS.
     APPEND P_BUKRS.
     ENDLOOP.
ENDIF.
IF T_AUART[] IS NOT INITIAL.
  LOOP AT T_AUART.
     TRANSLATE T_AUART-AUART TO UPPER CASE.
     P_AUART-SIGN = 'I'.
     P_AUART-OPTION = 'EQ'.
     P_AUART-LOW = T_AUART-AUART.
     APPEND P_AUART.
    ENDLOOP.
  ENDIF.
  SELECT   A~AUFNR  A~KTEXT  A~AUART A~CYCLE A~KOSTV A~BUKRS A~ERDAT
    INTO CORRESPONDING FIELDS OF TABLE T_ZNBDD
   FROM COAS AS A
   WHERE A~BUKRS IN P_BUKRS AND A~AUART IN P_AUART ."AND B~SPRAS = SY-LANGU  .
SORT T_ZNBDD BY BUKRS AUFNR AUART .
IF T_ZNBDD[] IS NOT INITIAL.
   SELECT * INTO CORRESPONDING FIELDS OF TABLE T_T003P
    FROM T003P
    FOR ALL ENTRIES IN T_ZNBDD
    WHERE  SPRAS = SY-LANGU AND AUART = T_ZNBDD-AUART.
 SORT T_T003P BY AUART.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE T_CSKT
    FROM CSKT
    FOR ALL ENTRIES IN T_ZNBDD
    WHERE KOKRS = '1000'  AND SPRAS = SY-LANGU AND KOSTL = T_ZNBDD-CYCLE.
 SORT T_CSKT BY KOSTL.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE T_CSKT3
    FROM CSKT
    FOR ALL ENTRIES IN T_ZNBDD
    WHERE KOKRS = '1000'  AND SPRAS = SY-LANGU AND KOSTL = T_ZNBDD-KOSTV.
 SORT T_CSKT3 BY KOSTL.

  SELECT * INTO CORRESPONDING FIELDS OF TABLE T_T001
    FROM T001
    WHERE BUKRS IN P_BUKRS .
  SORT T_T001 BY BUKRS .

  LOOP AT T_ZNBDD.
    READ TABLE T_T001 WITH KEY BUKRS = T_T001-BUKRS BINARY SEARCH.
     IF SY-SUBRC = 0.
        T_ZNBDD-BUTXT = T_T001-BUTXT.
     ENDIF.
    READ TABLE T_CSKT WITH KEY KOSTL = T_ZNBDD-CYCLE BINARY SEARCH.
     IF SY-SUBRC = 0.
        T_ZNBDD-KTEXT2 = T_CSKT-KTEXT.
       ENDIF.
      READ TABLE T_CSKT3 WITH KEY KOSTL = T_ZNBDD-KOSTV BINARY SEARCH .
     IF SY-SUBRC = 0.
        T_ZNBDD-KTEXT3 = T_CSKT3-KTEXT.
       ENDIF.
     READ TABLE T_T003P WITH KEY AUART = T_ZNBDD-AUART BINARY SEARCH.
     IF SY-SUBRC = 0.
        T_ZNBDD-TXT = T_T003P-TXT.
       ENDIF.
     MODIFY T_ZNBDD.
    ENDLOOP.
 R_MSG = '据读取成功,请查看T_ZNBDD表'.
 ELSE.
 R_MSG =  '数据读取失败,请重新更新检索条件' .
  ENDIF.

ENDFUNCTION.
