REPORT ZFI039.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1.


"项目结算调整过账
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZFI036'.
ENDIF.

*项目结算调整过账冲销
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZFI037'.
ENDIF.
