*&---------------------------------------------------------------------*
*&  包含                ZFI041_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P1 RADIOBUTTON GROUP RBG1 DEFAULT 'X',
            P2 RADIOBUTTON GROUP RBG1.
SELECTION-SCREEN END OF BLOCK B1 .

* 明细数据
SELECTION-SCREEN BEGIN OF SCREEN 0100 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-101.
PARAMETERS P_BUKRS2 TYPE T001-BUKRS .
PARAMETERS P_WERKS2 TYPE T001W-WERKS .
PARAMETERS P_GJAHR TYPE BKPF-GJAHR .
PARAMETERS P_MONAT TYPE BKPF-MONAT .
SELECT-OPTIONS S_LGORT FOR T001L-LGORT .
SELECT-OPTIONS S_MATNR FOR MARA-MATNR .
SELECT-OPTIONS S_VBELN FOR VBAK-VBELN .
SELECT-OPTIONS S_LIFNR FOR LFA1-LIFNR .
SELECTION-SCREEN END OF BLOCK B2 .
SELECTION-SCREEN END OF SCREEN 0100 .

* 汇总数据
SELECTION-SCREEN BEGIN OF SCREEN 0200 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-201.
PARAMETERS P_BUKRS3 TYPE T001-BUKRS .
PARAMETERS P_WERKS3 TYPE T001W-WERKS .
PARAMETERS P_GJAHR2 TYPE BKPF-GJAHR .
PARAMETERS P_MONAT2 TYPE BKPF-MONAT .
SELECT-OPTIONS S_MATNR2 FOR MARA-MATNR .
SELECT-OPTIONS S_VBELN2 FOR VBAK-VBELN .
SELECTION-SCREEN END OF BLOCK B3 .
SELECTION-SCREEN END OF SCREEN 0200 .
