*&---------------------------------------------------------------------*
*&  包含                ZFI004_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P1 RADIOBUTTON GROUP RBG1 DEFAULT 'X' USER-COMMAND UC1,
            P2 RADIOBUTTON GROUP RBG1.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
PARAMETERS P_BUKRS TYPE T001-BUKRS MODIF ID M21 .
SELECT-OPTIONS S_PSPID FOR PROJ-PSPID MODIF ID M21 .
PARAMETERS P_DATUM TYPE SY-DATUM DEFAULT '99991231' MODIF ID M21 .
PARAMETERS P3 AS CHECKBOX MODIF ID M21 .
SELECTION-SCREEN END OF BLOCK B2 .

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-003.
PARAMETERS P_BUKRS2 TYPE T001-BUKRS MODIF ID M31 .
SELECT-OPTIONS S_PSPID2 FOR PROJ-PSPID MODIF ID M31 .
SELECT-OPTIONS S_BUDAT FOR BKPF-BUDAT MODIF ID M31 .
SELECTION-SCREEN END OF BLOCK B3 .
