REPORT ZFI040_1.
"DES  项目明细账-PS
"DATE 20160621
"ADDED BY IT02
TABLES:BSEG,BKPF,PROJ,PRPS,SKAT .

TYPES:BEGIN OF TY_ITEM,
        BUKRS TYPE BUKRS,  "公司代码
        PSPID TYPE PS_PSPID, "项目定义
        XMMC  TYPE STRING,   "项目名称
*&--代码添加 BY HANDYBY 20.06.2017 10:28:51  BEGIN
        POSID TYPE PRPS-POSID,  "WBS外码
        POST1 TYPE PRPS-POST1,  "WBS描述
        STUFE TYPE PRPS-STUFE,  "WBS层级
*&--代码添加 BY HANDYBY 20.06.2017 10:28:51  END
        HKONT TYPE HKONT,     "科目
        KMMS  TYPE STRING,    "科目描述
        BELNR TYPE BELNR_D,    "会计凭证
        BUZEI TYPE BUZEI,     "凭证行号
        DMBTR TYPE DMBTR,    "本币码
        GJAHR TYPE GJAHR,   "会计年度
        BKTXT TYPE BKTXT,     "摘要
        JFJE  TYPE DMBTR,     "借方金额
        DFJE  TYPE DMBTR,     "贷方金额
        FX    TYPE STRING,    "方向
        WAERS TYPE WAERS,     "货币码
        YE    TYPE DMBTR,     "余额
        MATNR TYPE MATNR,     "物料号
        MAKTX TYPE MAKTX,     "物料描述
*&--代码添加 BY HANDYBY 20.06.2017 14:17:14  BEGIN
        MENGE TYPE BSEG-MENGE,  "数量
        MEINS TYPE BSEG-MEINS,  "单位
*&--代码添加 BY HANDYBY 20.06.2017 14:17:14  END
        SHKZG TYPE SHKZG,      "借贷标识
        XNEGP TYPE XNEGP,     "反记账
        XREF3 TYPE XREF3,     "参考码3
        BLART TYPE BLART,     "凭证类型
        BUDAT TYPE BUDAT,     "过账日期
        KUNNR TYPE KUNNR,      "客户
        KHMS  TYPE STRING,     "客户描述
        LIFNR TYPE LIFNR,     "供应商
        GYSMS TYPE STRING,   "供应商描述
        PROJK TYPE PS_PSP_PNR, "WBS
*&--代码添加 BY HANDYBY 18.08.2017 11:16:41  BEGIN
        AUFNR TYPE AUFK-AUFNR , " 内部订单
        KTEXT TYPE AUFK-KTEXT , " 内部订单描述
        KOSTL TYPE BSEG-KOSTL , " 成本中心
        LTEXT TYPE CSKT-LTEXT , " 成本中心描述
*&--代码添加 BY HANDYBY 18.08.2017 11:16:41  END
        ZUONR TYPE DZUONR,    "分配
        SEL,

      END OF TY_ITEM .

TYPES:BEGIN OF TY_QC,
        PSPID TYPE PS_PSPID, "项目定义
        HKONT TYPE HKONT,    "科目
        JFJE  TYPE DMBTR,     "借方金额
        DFJE  TYPE DMBTR,     "贷方金额
        FX    TYPE STRING,    "方向
        YE    TYPE DMBTR,     "余额
*        SL    TYPE BSEG-MENGE,  "数量
      END OF TY_QC .


DATA:GS_ITEM TYPE TY_ITEM,
     GT_ITEM TYPE TABLE OF TY_ITEM.


DATA:GS_ITEM_2 TYPE TY_ITEM,
     GT_ITEM_2 TYPE TABLE OF TY_ITEM.

DATA:GS_ITEM_QC TYPE TY_ITEM,
     GT_ITEM_QC TYPE TABLE OF TY_ITEM.

DATA:GS_ITEM_QC_2 TYPE TY_ITEM,
     GT_ITEM_QC_2 TYPE TABLE OF TY_ITEM.

DATA:GT_DATA   TYPE TABLE OF TY_ITEM,
     GS_DATA   TYPE TY_ITEM,
     GS_DATA_1 TYPE TY_ITEM.


DATA:GT_DATA_HZ TYPE TABLE OF TY_ITEM,
     GS_DATA_HZ TYPE TY_ITEM.

DATA:GT_DATA_SUM TYPE TABLE OF TY_ITEM,
     GS_DATA_SUM TYPE TY_ITEM.

DATA:GS_QC TYPE TY_QC,
     GT_QC TYPE TABLE OF TY_QC.

DATA:GT_SKAT TYPE TABLE OF SKAT,
     GS_SKAT TYPE SKAT.

DATA:GT_T001 TYPE  TABLE OF T001,
     GS_T001 TYPE T001.

DATA:GT_PROJ TYPE TABLE OF PROJ,
     GS_PROJ TYPE PROJ.

DATA:GT_PRPS TYPE TABLE OF PRPS,
     GS_PRPS TYPE PRPS.

DATA:GT_LFA1 TYPE TABLE OF LFA1,
     GS_LFA1 TYPE LFA1.

DATA:GT_MAKT TYPE TABLE OF MAKT,
     GS_MAKT TYPE MAKT.

DATA:GT_KNA1 TYPE TABLE OF KNA1,
     GS_KNA1 TYPE KNA1.

RANGES:R_HKONT FOR BSEG-HKONT.


FIELD-SYMBOLS:" <FS_DATA>  LIKE GS_DATA,
  <FS_QC>   LIKE GS_QC,
  <FS_ITEM> LIKE GS_ITEM.


*&---------------------------------------------------------------------*
*&      DEFINITION
*&---------------------------------------------------------------------*
DEFINE INIT_FIELDCAT.      "  ALV FIELDCAT SETTING
  GW_LVC-FIELDNAME = &1.
  GW_LVC-COLTEXT   = &2.
  GW_LVC-SCRTEXT_L = &2.
  GW_LVC-SCRTEXT_M = &2.
  GW_LVC-SCRTEXT_S = &2.
  GW_LVC-REPTEXT   = &2.
  GW_LVC-OUTPUTLEN = &3.
  GW_LVC-KEY = &4.
*  IF &1 = 'KUNNR'.
*    GW_LVC-NO_ZERO = 'X'.
*  ENDIF.
  IF &1 = 'JFJE' OR &1 = 'DFJE' OR &1 = 'YE' ." OR  &1 = 'YZCB'.
  GW_LVC-CFIELDNAME = 'WAERS'.
 ENDIF.
* IF &1 = 'YZCB'.
*   GW_LVC-NO_SIGN = ''.
*   GW_LVC-DECIMALS = 2.
* ENDIF.
* IF &1 = 'JZKM' OR &1 = 'DFKM' .
*   gw_lvc-f4availabl = 'X'.
* ENDIF.
  GW_LVC-CHECKBOX = &5.
  GW_LVC-EDIT = &6.
*  GW_LVC-FIX_COLUMN =  &7.
  GW_LVC-HOTSPOT   = &7.
  GW_LVC-REF_TABLE = &8.
  GW_LVC-REF_FIELD = &9.
  APPEND GW_LVC TO GT_LVC.
  CLEAR GW_LVC.
END-OF-DEFINITION.

*&---------------------------------------------------------------------*
*&      ALV DECLARATION
*&---------------------------------------------------------------------*
TYPE-POOLS: SLIS.

DATA: GT_LVC           TYPE LVC_T_FCAT,
      GT_SORT          TYPE LVC_T_SORT,
      GW_LAYOUT        TYPE LVC_S_LAYO,                    "ALV的格式
      GW_VARIANT       TYPE DISVARIANT,
      GW_GRID_SETTINGS TYPE LVC_S_GLAY,
      GW_LVC           TYPE LVC_S_FCAT,
      GW_SORT          TYPE LVC_S_SORT,
      GW_GRID_SETTING  TYPE LVC_S_GLAY,
      G_REPID          LIKE SY-REPID,                      "SY-REPID 指 当前的主程序
      GT_EVENTS        TYPE SLIS_T_EVENT WITH HEADER LINE, "保存AVL事件
      GW_EVENTS        LIKE LINE OF GT_EVENTS.
DATA: GT_EXCLUDE TYPE SLIS_T_EXTAB,
      GS_EXCLUDE TYPE SLIS_EXTAB.

DATA: GR_ALVGRID TYPE REF TO CL_GUI_ALV_GRID.

DATA: GT_ROWS TYPE LVC_T_ROW,
      GT_ROID TYPE LVC_T_ROID,
      WA_ROWS TYPE LVC_S_ROW,
      WA_ROID TYPE LVC_S_ROID.
DATA: GS_VARIANT TYPE DISVARIANT.
DATA: GW_ISTABLE TYPE LVC_S_STBL.

DATA:G_WAERS TYPE WAERS .  "货币码



************************************************************************
* GLOBAL VARIANT
************************************************************************


************************************************************************
* CONSTANT
************************************************************************

************************************************************************
* SELECTION SCREEN
************************************************************************
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-001.
PARAMETER:
P_BUKRS  TYPE BKPF-BUKRS OBLIGATORY.                      "公司代码
SELECT-OPTIONS: S_BUDAT  FOR BKPF-BUDAT OBLIGATORY,    "过账日期
                S_PSPID  FOR PROJ-PSPID  OBLIGATORY,
                S_HKONT  FOR BSEG-HKONT .

SELECTION-SCREEN END OF BLOCK BLK1.
*&---------------------------------------------------------------------*
*& 初始化处理
*&---------------------------------------------------------------------*
INITIALIZATION.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1001000000'.
  R_HKONT-HIGH = '1001999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1002000000'.
  R_HKONT-HIGH = '1002999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1012000000'.
  R_HKONT-HIGH = '1012999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1121000000'.
  R_HKONT-HIGH = '1123999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1241000000'.
  R_HKONT-HIGH = '1241999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
*&--代码注释 BY HANDYBY 20.06.2017 19:14:11  BEGIN
*    R_HKONT-LOW = '1401000000'.
*  R_HKONT-HIGH = '1401999999'.
*&--代码注释 BY HANDYBY 20.06.2017 19:14:11  END
*&--代码添加 BY HANDYBY 20.06.2017 19:13:58  BEGIN
  R_HKONT-LOW = '1403000000'.
  R_HKONT-HIGH = '1403999999'.
*&--代码添加 BY HANDYBY 20.06.2017 19:13:58  END
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:14:29  BEGIN
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1406000000'.
  R_HKONT-HIGH = '1406999999'.
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:14:29  END
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1408000000'.
  R_HKONT-HIGH = '1408999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '2201000000'.
  R_HKONT-HIGH = '2202999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1121000000'.
  R_HKONT-HIGH = '1123999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1241000000'.
  R_HKONT-HIGH = '1241999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1401000000'.
  R_HKONT-HIGH = '1401999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '1408000000'.
  R_HKONT-HIGH = '1408999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '2201000000'.
  R_HKONT-HIGH = '2203999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '2221030500'.
  R_HKONT-HIGH = '2221030599'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '2241000000'.
  R_HKONT-HIGH = '2241999999'.
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '5401000000'.
*&--代码注释 BY HANDYBY 20.06.2017 20:54:55  BEGIN
*    R_HKONT-HIGH = '5401999999'.
*&--代码注释 BY HANDYBY 20.06.2017 20:54:55  END
*&--代码添加 BY HANDYBY 20.06.2017 20:55:00  BEGIN
  R_HKONT-HIGH = '5401030100'.
  APPEND R_HKONT.

  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '5401030102'.
  R_HKONT-HIGH = '5401999999'.
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 20:55:00  END
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:14:51  BEGIN
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '5402000000'.
*&--代码注释 BY HANDYBY 22.06.2017 11:18:32  BEGIN
*    R_HKONT-HIGH = '5402999999'.
*&--代码注释 BY HANDYBY 22.06.2017 11:18:32  END
*&--代码添加 BY HANDYBY 22.06.2017 11:18:37  BEGIN
  R_HKONT-HIGH = '5402010100'.
  APPEND R_HKONT.

  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '5402010102'.
  R_HKONT-HIGH = '5402999999'.
*&--代码添加 BY HANDYBY 22.06.2017 11:18:37  END
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:14:51  END
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '6001000000'.
  R_HKONT-HIGH = '6001999999'.
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:15:15  BEGIN
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '6404000000'.
  R_HKONT-HIGH = '6404999999'.
  APPEND R_HKONT.
*&--代码添加 BY HANDYBY 20.06.2017 19:15:15  END
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '6401000000'.
*&--代码注释 BY HANDYBY 20.06.2017 20:42:42  BEGIN
*    R_HKONT-HIGH = '6401999999'.
*&--代码注释 BY HANDYBY 20.06.2017 20:42:42  END
*&--代码添加 BY HANDYBY 20.06.2017 20:42:46  BEGIN
  R_HKONT-HIGH = '6401030100'.
  APPEND R_HKONT .

  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '6401030102'.
  R_HKONT-HIGH = '6401999999'.
  APPEND R_HKONT .
*&--代码添加 BY HANDYBY 20.06.2017 20:42:46  END
  APPEND R_HKONT.
  R_HKONT-SIGN = 'I'.
  R_HKONT-OPTION = 'BT'.
  R_HKONT-LOW = '8000000000'.
  R_HKONT-HIGH = '8999999999'.
  APPEND R_HKONT.
  CLEAR R_HKONT.
  R_HKONT = 'EEQ'.
  R_HKONT-LOW = '5401020101'.
  APPEND R_HKONT.
*&---------------------------------------------------------------------*
*& 选择屏幕控制
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.
*  PERFORM XXXXXXX.

*&---------------------------------------------------------------------*
*& 参数输入检查
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN.
*  PERFORM XXXXXXX.

*&---------------------------------------------------------------------*
*& 程序开始处理
*&---------------------------------------------------------------------*
START-OF-SELECTION.

  "权限检查检查公司代码
  PERFORM FRM_AUTH_CHECK USING '03'.
  IF SY-SUBRC NE 0.
    MESSAGE I011(ZFICO01) WITH P_BUKRS DISPLAY LIKE 'E'.
    STOP.
  ENDIF.

  PERFORM FRM_GET_DATA. "取数逻辑
  PERFORM FRM_DEAL_DATA."处理数逻辑
  PERFORM FRM_ALV_SHOW. "ALV显示

  "*&---------------------------------------------------------------------*
*& 程序结束处理
*&---------------------------------------------------------------------*
END-OF-SELECTION.
*&---------------------------------------------------------------------*
*&      Form  FRM_AUTH_CHECK
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_0401   text
*----------------------------------------------------------------------*
FORM FRM_AUTH_CHECK USING VALUE(P_ACTVT).
  AUTHORITY-CHECK OBJECT 'F_BKPF_BUK' ID 'ACTVT' FIELD P_ACTVT
                                      ID 'BUKRS' FIELD P_BUKRS.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_GET_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_GET_DATA .

  "取出项目项目信息
  SELECT * INTO TABLE GT_PROJ
    FROM PROJ
    WHERE PSPID IN S_PSPID
                    AND   VBUKR EQ P_BUKRS  .
  SORT GT_PROJ BY PSPNR .


  CHECK GT_PROJ IS NOT INITIAL .

  "取WBS信息
*&--代码注释 BY HANDYBY 20.06.2017 14:20:10  BEGIN
*    SELECT * INTO TABLE GT_PRPS
*    FROM PRPS
*    WHERE POSID IN S_PSPID.
*&--代码注释 BY HANDYBY 20.06.2017 14:20:10  END
*&--代码添加 BY HANDYBY 20.06.2017 14:20:18  BEGIN
  SELECT * INTO TABLE GT_PRPS
    FROM PRPS
      FOR ALL ENTRIES IN GT_PROJ
    WHERE PSPHI = GT_PROJ-PSPNR .
*&--代码添加 BY HANDYBY 20.06.2017 14:20:18  END

  .
  DATA: LT_PRPS LIKE GT_PRPS,
        LS_PRPS LIKE LINE OF LT_PRPS.
  MOVE-CORRESPONDING GT_PRPS TO LT_PRPS .

  SORT GT_PRPS BY PSPNR.
  SORT LT_PRPS BY POSID .

  CHECK GT_PRPS IS NOT INITIAL .

*&--代码添加 BY HANDYBY 20.06.2017 20:40:53  BEGIN
*  DELETE S_HKONT[] WHERE LOW = '5401030101' .
*  DELETE S_HKONT[] WHERE LOW = '6401030101' .
*  DELETE S_HKONT[] WHERE LOW = '5402010101' .
*&--代码添加 BY HANDYBY 20.06.2017 20:40:53  END

  "取出查询期间过账信息
  SELECT A~BUKRS  A~GJAHR A~BELNR  A~BUDAT  A~BKTXT A~BLART
    B~BUZEI B~HKONT B~SHKZG B~DMBTR  B~MATNR B~XREF3 B~XNEGP
     B~KUNNR B~LIFNR      B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
*    B~ZUONR AS POSID
    B~MENGE  B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
    INTO CORRESPONDING FIELDS OF TABLE GT_ITEM_2
    FROM BKPF AS A
    INNER JOIN  BSEG AS B
    ON A~BUKRS = B~BUKRS
    AND A~GJAHR = B~GJAHR
    AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  END
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  BEGIN
*    WHERE A~BUKRS EQ P_BUKRS
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  END
*&--代码添加 BY HANDYBY 20.06.2017 20:36:48  BEGIN
    WHERE
          A~BUKRS EQ P_BUKRS
*&--代码添加 BY HANDYBY 20.06.2017 20:36:48  END
   AND A~BUDAT IN S_BUDAT
   AND A~BLART NOT IN ('SC','AB' , 'SA')
   AND B~HKONT IN S_HKONT
   AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 14:40:36  BEGIN
*    AND B~PROJK IN  ( SELECT PSPNR  FROM  PRPS
*                    WHERE  POSID IN S_PSPID
*                AND PBUKR  EQ P_BUKRS ) .
*&--代码注释 BY HANDYBY 20.06.2017 14:40:36  END
*&--代码添加 BY HANDYBY 20.06.2017 14:40:43  BEGIN
    AND B~PROJK = GT_PRPS-PSPNR  .

**& 励丰1700 1710 SA凭证类型
  "取出查询期间过账信息
  SELECT A~BUKRS  A~GJAHR A~BELNR  A~BUDAT  A~BKTXT A~BLART
    B~BUZEI B~HKONT B~SHKZG B~DMBTR  B~MATNR B~XREF3 B~XNEGP
     B~KUNNR B~LIFNR      B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
    B~ZUONR AS POSID
    B~MENGE  B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
    APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM_2
    FROM BKPF AS A
    INNER JOIN  BSEG AS B
    ON A~BUKRS = B~BUKRS
    AND A~GJAHR = B~GJAHR
    AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  END
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  BEGIN
*    WHERE A~BUKRS EQ P_BUKRS
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  END
*&--代码添加 BY HANDYBY 20.06.2017 20:36:48  BEGIN
    WHERE
          A~BUKRS EQ P_BUKRS
*&--代码添加 BY HANDYBY 20.06.2017 20:36:48  END
   AND A~BUDAT IN S_BUDAT
   AND A~BLART EQ 'SA'
   AND B~HKONT IN S_HKONT
   AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 14:40:36  BEGIN
*    AND B~PROJK IN  ( SELECT PSPNR  FROM  PRPS
*                    WHERE  POSID IN S_PSPID
*                AND PBUKR  EQ P_BUKRS ) .
*&--代码注释 BY HANDYBY 20.06.2017 14:40:36  END
*&--代码添加 BY HANDYBY 20.06.2017 14:40:43  BEGIN
    AND B~PROJK = GT_PRPS-PSPNR  .

* 补充5401和6401这2个科目的过账信息
  SELECT A~BUKRS  A~GJAHR A~BELNR  A~BUDAT  A~BKTXT A~BLART
B~BUZEI B~HKONT B~SHKZG B~DMBTR  B~MATNR B~XREF3 B~XNEGP
B~KUNNR B~LIFNR      "B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
B~ZUONR AS POSID
B~MENGE  B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM_2
FROM BKPF AS A
INNER JOIN  BSEG AS B
ON A~BUKRS = B~BUKRS
AND A~GJAHR = B~GJAHR
AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  BEGIN
FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 14:40:10  END
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  BEGIN
*    WHERE A~BUKRS EQ P_BUKRS
*&--代码注释 BY HANDYBY 20.06.2017 20:36:43  END
*&--代码添加 BY HANDYBY 20.06.2017 20:36:48  BEGIN
WHERE A~BUKRS EQ P_BUKRS
      AND A~BUDAT IN S_BUDAT
*             AND A~BLART NOT IN ('SC','AB')
      AND B~HKONT IN S_HKONT
      AND B~HKONT IN ( '5401030101','6401030101','5402010101','5401020101' )
      AND B~ZUONR = GT_PRPS-POSID+0(18) .
*&--代码添加 BY HANDYBY 20.06.2017 14:40:43  END

*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  BEGIN
  DATA L_INDEX TYPE SY-TABIX .
  LOOP AT GT_ITEM_2 INTO GS_ITEM_2 .
    L_INDEX = SY-TABIX .
    TRANSLATE GS_ITEM_2-PROJK TO UPPER CASE .
    TRANSLATE GS_ITEM_2-POSID TO UPPER CASE .
    READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM_2-PROJK BINARY SEARCH .
    IF SY-SUBRC = 0 .
      GS_ITEM_2-POSID = GS_PRPS-POSID .
      GS_ITEM_2-POST1 = GS_PRPS-POST1 .
      GS_ITEM_2-STUFE = GS_PRPS-STUFE .
    ELSE.
      READ TABLE LT_PRPS INTO LS_PRPS WITH KEY POSID = GS_ITEM_2-POSID BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_2-POST1 = LS_PRPS-POST1 .
        GS_ITEM_2-STUFE = LS_PRPS-STUFE .
        GS_ITEM_2-PROJK = LS_PRPS-PSPNR .
      ENDIF.
    ENDIF.
    IF GS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = GS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_2-PSPID = GS_PROJ-PSPID .
        GS_ITEM_2-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    IF LS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = LS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_2-PSPID = GS_PROJ-PSPID .
        GS_ITEM_2-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    MODIFY GT_ITEM_2 FROM GS_ITEM_2 INDEX L_INDEX .
    CLEAR GS_PRPS .
    CLEAR LS_PRPS .
    CLEAR GS_PROJ .
    CLEAR GS_ITEM_2 .
    CLEAR L_INDEX .
  ENDLOOP.
*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  END


  SORT GT_ITEM_2 BY PROJK  HKONT .

  "取出查询期间过账信息
  SELECT A~BUKRS  A~GJAHR A~BELNR  A~BUDAT  A~BKTXT A~BLART
    B~BUZEI B~HKONT B~SHKZG B~DMBTR  B~MATNR B~XREF3 B~XNEGP
      B~KUNNR B~LIFNR  B~ZUONR AS POSID
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
*     B~PROJK
     B~MENGE B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
    APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM
    FROM BKPF AS A
    INNER JOIN  BSEG AS B
    ON A~BUKRS = B~BUKRS
    AND A~GJAHR = B~GJAHR
    AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 20:33:24  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 20:33:24  END
     WHERE
        A~BUKRS EQ P_BUKRS
   AND A~BUDAT IN S_BUDAT
   AND A~BLART EQ 'SC'
   AND B~HKONT IN S_HKONT
     AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 20:33:36  BEGIN
*    AND B~ZUONR IN ( SELECT PSPID  FROM  PROJ
*                    WHERE  PSPID IN S_PSPID
*                AND VBUKR  EQ P_BUKRS ) .
*&--代码注释 BY HANDYBY 20.06.2017 20:33:36  END
*&--代码添加 BY HANDYBY 20.06.2017 20:33:47  BEGIN
    AND B~ZUONR = GT_PRPS-POSID+0(18) .
*&--代码添加 BY HANDYBY 20.06.2017 20:33:47  END

*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  BEGIN
  LOOP AT GT_ITEM INTO GS_ITEM .
    L_INDEX = SY-TABIX .
    TRANSLATE GS_ITEM_2-PROJK TO UPPER CASE .
    TRANSLATE GS_ITEM_2-POSID TO UPPER CASE .
    READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM-PROJK BINARY SEARCH .
    IF SY-SUBRC = 0 .
      GS_ITEM-POSID = GS_PRPS-POSID .
      GS_ITEM-POST1 = GS_PRPS-POST1 .
      GS_ITEM-STUFE = GS_PRPS-STUFE .
    ELSE.
      READ TABLE LT_PRPS INTO LS_PRPS WITH KEY POSID = GS_ITEM-POSID BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM-POST1 = LS_PRPS-POST1 .
        GS_ITEM-STUFE = LS_PRPS-STUFE .
        GS_ITEM-PROJK = LS_PRPS-PSPNR .
      ENDIF.
    ENDIF.
    IF GS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = GS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM-PSPID = GS_PROJ-PSPID .
        GS_ITEM-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    IF LS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = LS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM-PSPID = GS_PROJ-PSPID .
        GS_ITEM-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    MODIFY GT_ITEM FROM GS_ITEM INDEX L_INDEX .
    CLEAR GS_PROJ .
    CLEAR LS_PRPS .
    CLEAR GS_PRPS .
    CLEAR GS_ITEM .
    CLEAR L_INDEX .
  ENDLOOP.
*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  END

  SORT GT_ITEM BY PSPID HKONT BUDAT.


  "查询小于最小期间的过账明细
  SELECT A~BUKRS  A~GJAHR A~BELNR
     B~BUZEI B~HKONT B~SHKZG B~DMBTR B~XNEGP
      B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
     B~ZUONR AS POSID
     B~MENGE B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
     INTO CORRESPONDING FIELDS OF TABLE GT_ITEM_QC_2
     FROM BKPF AS A
     INNER JOIN  BSEG AS B
     ON A~BUKRS = B~BUKRS
     AND A~GJAHR = B~GJAHR
     AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  END
      WHERE
      A~BUKRS EQ P_BUKRS
    AND A~BUDAT < S_BUDAT-LOW
    AND A~BLART EQ 'SA'
    AND B~HKONT IN S_HKONT
    AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 21:02:37  BEGIN
*    AND B~PROJK IN ( SELECT PSPNR  FROM  PRPS
*                     WHERE  POSID IN S_PSPID
*                 AND PBUKR  EQ P_BUKRS )
*&--代码注释 BY HANDYBY 20.06.2017 21:02:37  END
*&--代码添加 BY HANDYBY 20.06.2017 21:02:53  BEGIN
    AND B~PROJK = GT_PRPS-PSPNR .

  "查询小于最小期间的过账明细
  SELECT A~BUKRS  A~GJAHR A~BELNR
     B~BUZEI B~HKONT B~SHKZG B~DMBTR B~XNEGP
      B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
*   B~ZUONR AS POSID
     B~MENGE B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
     APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM_QC_2
     FROM BKPF AS A
     INNER JOIN  BSEG AS B
     ON A~BUKRS = B~BUKRS
     AND A~GJAHR = B~GJAHR
     AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  END
      WHERE
      A~BUKRS EQ P_BUKRS
    AND A~BUDAT < S_BUDAT-LOW
    AND A~BLART NOT IN ('SC','AB' ,'SA')
    AND B~HKONT IN S_HKONT
    AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 21:02:37  BEGIN
*    AND B~PROJK IN ( SELECT PSPNR  FROM  PRPS
*                     WHERE  POSID IN S_PSPID
*                 AND PBUKR  EQ P_BUKRS )
*&--代码注释 BY HANDYBY 20.06.2017 21:02:37  END
*&--代码添加 BY HANDYBY 20.06.2017 21:02:53  BEGIN
    AND B~PROJK = GT_PRPS-PSPNR .


*&--代码添加 BY HANDYBY 20.06.2017 21:02:53  END
  SELECT A~BUKRS  A~GJAHR A~BELNR
   B~BUZEI B~HKONT B~SHKZG B~DMBTR B~XNEGP
*      B~PROJK
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
 B~ZUONR AS POSID
   B~MENGE B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
   APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM_QC_2
   FROM BKPF AS A
   INNER JOIN  BSEG AS B
   ON A~BUKRS = B~BUKRS
   AND A~GJAHR = B~GJAHR
   AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  BEGIN
  FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 21:02:12  END
    WHERE
    A~BUKRS EQ P_BUKRS
        AND A~BUDAT < S_BUDAT-LOW
*         AND A~BLART NOT IN ('SC','AB')
    AND B~HKONT IN S_HKONT
      AND B~HKONT IN ( '5401030101','6401030101','5402010101','5401020101' )
     AND B~ZUONR = GT_PRPS-POSID+0(18) .

*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  BEGIN
  LOOP AT GT_ITEM_QC_2 INTO GS_ITEM_QC_2 .
    L_INDEX = SY-TABIX .
    TRANSLATE GS_ITEM_2-PROJK TO UPPER CASE .
    TRANSLATE GS_ITEM_2-POSID TO UPPER CASE .
    READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM_QC_2-PROJK BINARY SEARCH .
    IF SY-SUBRC = 0 .
      GS_ITEM_QC_2-POSID = GS_PRPS-POSID .
      GS_ITEM_QC_2-POST1 = GS_PRPS-POST1 .
      GS_ITEM_QC_2-STUFE = GS_PRPS-STUFE .
    ELSE.
      READ TABLE LT_PRPS INTO LS_PRPS WITH KEY POSID = GS_ITEM_QC_2-POSID BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC_2-POST1 = LS_PRPS-POST1 .
        GS_ITEM_QC_2-STUFE = LS_PRPS-STUFE .
        GS_ITEM_QC_2-PROJK = LS_PRPS-PSPNR .
      ENDIF.
    ENDIF.
    IF GS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = GS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC_2-PSPID = GS_PROJ-PSPID .
        GS_ITEM_QC_2-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    IF LS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = LS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC_2-PSPID = GS_PROJ-PSPID .
        GS_ITEM_QC_2-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    MODIFY GT_ITEM_QC_2 FROM GS_ITEM_QC_2 INDEX L_INDEX .
    CLEAR GS_PRPS .
    CLEAR LS_PRPS .
    CLEAR GS_PROJ .
    CLEAR GS_ITEM_QC_2 .
    CLEAR L_INDEX .
  ENDLOOP.
*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  END

  SORT GT_ITEM_QC_2 BY PROJK HKONT .

  "查询小于最小期间的过账明细
  SELECT A~BUKRS  A~GJAHR A~BELNR   A~BLART
    B~BUZEI B~HKONT B~SHKZG B~DMBTR  B~XNEGP
     B~ZUONR AS POSID
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  BEGIN
*    B~PROJK
    B~MENGE B~MEINS
*&--代码添加 BY HANDYBY 20.06.2017 21:11:33  END
    APPENDING CORRESPONDING FIELDS OF TABLE GT_ITEM_QC
    FROM BKPF AS A
    INNER JOIN  BSEG AS B
    ON A~BUKRS = B~BUKRS
    AND A~GJAHR = B~GJAHR
    AND A~BELNR = B~BELNR
*&--代码添加 BY HANDYBY 20.06.2017 21:04:18  BEGIN
    FOR ALL ENTRIES IN GT_PRPS
*&--代码添加 BY HANDYBY 20.06.2017 21:04:18  END
     WHERE
        A~BUKRS EQ P_BUKRS
   AND A~BUDAT < S_BUDAT-LOW
   AND A~BLART EQ 'SC'
   AND B~HKONT IN S_HKONT
     AND B~HKONT IN R_HKONT
*&--代码注释 BY HANDYBY 20.06.2017 21:05:55  BEGIN
*    AND B~ZUONR IN ( SELECT PSPID  FROM  PROJ
*                    WHERE  PSPID IN S_PSPID
*                AND VBUKR  EQ P_BUKRS )
*&--代码注释 BY HANDYBY 20.06.2017 21:05:55  END
*&--代码添加 BY HANDYBY 20.06.2017 21:06:03  BEGIN
    AND B~ZUONR = GT_PRPS-POSID+0(18) .
*&--代码添加 BY HANDYBY 20.06.2017 21:06:03  END

*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  BEGIN
  LOOP AT GT_ITEM_QC INTO GS_ITEM_QC .
    L_INDEX = SY-TABIX .
    TRANSLATE GS_ITEM_2-PROJK TO UPPER CASE .
    TRANSLATE GS_ITEM_2-POSID TO UPPER CASE .
    READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM_QC-PROJK BINARY SEARCH .
    IF SY-SUBRC = 0 .
      GS_ITEM_QC-POSID = GS_PRPS-POSID .
      GS_ITEM_QC-POST1 = GS_PRPS-POST1 .
      GS_ITEM_QC-STUFE = GS_PRPS-STUFE .
    ELSE.
      READ TABLE LT_PRPS INTO LS_PRPS WITH KEY POSID = GS_ITEM_QC-POSID BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC-POST1 = LS_PRPS-POST1 .
        GS_ITEM_QC-STUFE = LS_PRPS-STUFE .
        GS_ITEM_QC-PROJK = LS_PRPS-PSPNR .
      ENDIF.
    ENDIF.
    IF GS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = GS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC-PSPID = GS_PROJ-PSPID .
        GS_ITEM_QC-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    IF LS_PRPS IS NOT INITIAL .
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR = LS_PRPS-PSPHI BINARY SEARCH .
      IF SY-SUBRC = 0 .
        GS_ITEM_QC-PSPID = GS_PROJ-PSPID .
        GS_ITEM_QC-XMMC = GS_PROJ-POST1 .
      ENDIF.
    ENDIF.
    MODIFY GT_ITEM_QC FROM GS_ITEM_QC INDEX L_INDEX .
    CLEAR GS_PRPS .
    CLEAR LS_PRPS .
    CLEAR GS_PROJ .
    CLEAR GS_ITEM_QC .
    CLEAR L_INDEX .
  ENDLOOP.
*&--代码添加 BY HANDYBY 21.06.2017 09:32:19  END

  SORT GT_ITEM_QC BY PSPID HKONT BUDAT.

  "查询供应商主数据信息
  SELECT * INTO TABLE GT_LFA1
    FROM LFA1
    .
  SORT GT_LFA1 BY LIFNR .

  "查询物料主数据信息
  SELECT * INTO TABLE GT_MAKT
    FROM MAKT
    WHERE SPRAS = '1'.

  SORT GT_MAKT BY MATNR .

  "查询客户主数据信息
  SELECT * INTO TABLE GT_KNA1
    FROM KNA1
    .

  SORT GT_KNA1 BY KUNNR.

  "查询总账科目主数据信息
  SELECT * INTO TABLE GT_SKAT
    FROM SKAT
    WHERE SPRAS = '1'
    AND KTOPL = '1000'.
  SORT GT_SKAT BY SAKNR .

  "查询公司的本币货币码
  SELECT SINGLE WAERS INTO G_WAERS FROM T001 WHERE  BUKRS = P_BUKRS .

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_DEAL_DATA
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_DEAL_DATA .
  "按项目号 、科目维度 汇总期初
  LOOP AT GT_ITEM_QC INTO GS_ITEM_QC .
    "项目
    CLEAR:GS_QC.
    GS_QC-PSPID = GS_ITEM_QC-PSPID.
    GS_QC-HKONT = GS_ITEM_QC-HKONT .
    IF GS_ITEM_QC-SHKZG EQ 'S' .
      IF GS_ITEM_QC-XNEGP EQ ''.
        GS_QC-JFJE = GS_ITEM_QC-DMBTR.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ELSE.
        GS_QC-DFJE = GS_ITEM_QC-DMBTR * -1.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ENDIF.
    ELSE.
      IF GS_ITEM_QC-XNEGP EQ ''.
        GS_QC-DFJE = GS_ITEM_QC-DMBTR.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ELSE.
        GS_QC-JFJE = GS_ITEM_QC-DMBTR * -1.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ENDIF.
    ENDIF.

  ENDLOOP.
  SORT GT_QC BY PSPID HKONT.
  DATA:POSID TYPE PS_POSID,
       PSPID TYPE PS_PSPID.
  LOOP AT GT_ITEM_QC_2 INTO GS_ITEM_QC_2.
    CLEAR :GS_QC .
    AT NEW PROJK.
      CLEAR:PSPID.
      READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM_QC_2-PROJK BINARY SEARCH .
      IF SY-SUBRC EQ 0 .
        READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR  = GS_PRPS-PSPHI BINARY SEARCH .
        IF SY-SUBRC EQ 0 .
          PSPID = GS_PROJ-PSPID.
        ENDIF.
      ENDIF.
    ENDAT.
    GS_ITEM_QC_2-PSPID = PSPID.
    MODIFY GT_ITEM_QC_2 FROM GS_ITEM_QC_2.
    GS_QC-PSPID = PSPID.
    GS_QC-HKONT = GS_ITEM_QC_2-HKONT.
    IF GS_ITEM_QC_2-SHKZG EQ 'S' .
      IF GS_ITEM_QC_2-XNEGP EQ ''.
        GS_QC-JFJE = GS_ITEM_QC_2-DMBTR.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ELSE.
        GS_QC-DFJE = GS_ITEM_QC_2-DMBTR * -1.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ENDIF.
    ELSE.
      IF GS_ITEM_QC-XNEGP EQ ''.
        GS_QC-DFJE = GS_ITEM_QC_2-DMBTR.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ELSE.
        GS_QC-JFJE = GS_ITEM_QC_2-DMBTR * -1.
        COLLECT GS_QC INTO GT_QC.
        CONTINUE.
      ENDIF.
    ENDIF.

  ENDLOOP.

  "先赋值项目订单号
  LOOP AT GT_ITEM_2 INTO GS_ITEM_2 .
    AT NEW PROJK.
      CLEAR:PSPID.
      READ TABLE GT_PRPS INTO GS_PRPS WITH KEY PSPNR = GS_ITEM_2-PROJK BINARY SEARCH .
      IF SY-SUBRC EQ 0 .
        READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPNR  = GS_PRPS-PSPHI BINARY SEARCH .
        IF SY-SUBRC EQ 0 .
          PSPID = GS_PROJ-PSPID.

        ENDIF.
      ENDIF.
    ENDAT.
    GS_ITEM_2-PSPID = PSPID.
    MODIFY GT_ITEM_2 FROM GS_ITEM_2.
  ENDLOOP.

  APPEND LINES OF GT_ITEM_2 TO GT_ITEM .

  "先按过账明细按项目号 、科目 排序
  SORT GT_ITEM BY PSPID HKONT.
  DATA:XH TYPE I VALUE 0 .
  CLEAR:XH.
  DATA:JFXJ TYPE DMBTR, "借方小计
       DFXJ TYPE DMBTR. "贷方小计

  DATA:XMMC TYPE STRING.

  "过账明细处理：物料名称、借贷金额、供应商明细、客户明细 到 GT_DATA
  LOOP AT GT_ITEM ASSIGNING <FS_ITEM>.
    " xh = xh + 1.
    CLEAR:GS_DATA.
    MOVE <FS_ITEM> TO GS_DATA.

    "物料名称
    READ TABLE GT_MAKT INTO GS_MAKT WITH KEY MATNR = GS_DATA-MATNR BINARY SEARCH .
    IF SY-SUBRC EQ 0 .

      GS_DATA-MAKTX = GS_MAKT-MAKTX.
    ENDIF.

    "客户名称
    READ TABLE GT_KNA1 INTO GS_KNA1 WITH KEY KUNNR = GS_DATA-KUNNR BINARY SEARCH .
    IF SY-SUBRC EQ 0 .
      GS_DATA-KHMS = GS_KNA1-NAME1.
    ENDIF.


    "供应商名称
    READ TABLE GT_LFA1 INTO GS_LFA1 WITH KEY LIFNR = GS_DATA-LIFNR BINARY SEARCH .
    IF SY-SUBRC EQ 0 .
      GS_DATA-GYSMS = GS_LFA1-NAME1.

    ENDIF.

    "物料名称
    READ TABLE GT_MAKT INTO GS_MAKT WITH KEY MATNR = GS_DATA-MATNR BINARY SEARCH .
    IF SY-SUBRC EQ 0 .
      GS_DATA-MAKTX = GS_MAKT-MAKTX .
    ENDIF.

    "借贷方金额
    IF GS_DATA-SHKZG EQ 'S'.
      IF GS_DATA-XNEGP EQ ''.
        GS_DATA-JFJE = GS_DATA-DMBTR .
        GS_DATA-FX = '借'.
*        jfxj = jfxj + gs_data-jfje ."借方小计
      ELSE.
        GS_DATA-DFJE = GS_DATA-DMBTR  * -1 .
        GS_DATA-FX = '贷'.
*        dfxj = dfxj + gs_data-dfje . "贷方小计
      ENDIF.


    ELSE.

      IF GS_DATA-XNEGP EQ ''.
        GS_DATA-DFJE = GS_DATA-DMBTR .
        GS_DATA-FX = '贷'.
*        dfxj = dfxj + gs_data-dfje . "贷方小计
      ELSE.
        GS_DATA-JFJE = GS_DATA-DMBTR  * -1 .
        GS_DATA-FX = '借'.
*        jfxj = jfxj + gs_data-jfje ."借方小计
      ENDIF.
    ENDIF.

    "余额
    GS_DATA-YE = GS_DATA-JFJE - GS_DATA-DFJE.
    GS_DATA-WAERS = G_WAERS.    "货币码
    APPEND GS_DATA TO GT_DATA.



  ENDLOOP.

  "再添加期初合计 到 gt_data.
  SORT GT_QC BY PSPID ASCENDING HKONT DESCENDING.
  DATA:QC_TABIX TYPE I,
       L_TABIX  TYPE I.

  SORT GT_DATA BY PSPID HKONT .

  LOOP AT GT_QC INTO GS_QC .
    QC_TABIX = SY-TABIX .
    CLEAR:GS_DATA.
    GS_DATA-BUKRS = P_BUKRS. "公司代码
    GS_DATA-PSPID = GS_QC-PSPID. "项目
    GS_DATA-HKONT = GS_QC-HKONT.  "科目
    GS_DATA-JFJE = GS_QC-JFJE.  "借方金额
    GS_DATA-DFJE = GS_QC-DFJE.  "贷方金额
    GS_DATA-YE =  GS_DATA-JFJE - GS_DATA-DFJE  .
    IF GS_DATA-YE > 0 .
      GS_DATA-FX =  '借'.

    ELSEIF  GS_DATA-YE < 0 .
      GS_DATA-FX = '贷'.
    ELSE.
      GS_DATA-FX = '平'.
    ENDIF.

    GS_DATA-WAERS = G_WAERS.    "货币码
    GS_DATA-BKTXT = '期初余额'.     "摘要
    "汇总期初余额明细插入到GT_DATA 明细
    "1:先按项目、科目查找到GT_DATA明细就插入对应的前行
    "2:1不满足就按项目查找 就插入到对应的前行
    "3:1、2不满足就直接直接插入到GT_DATA_HZ
    READ TABLE GT_DATA INTO GS_DATA_1 WITH KEY PSPID = GS_DATA-PSPID HKONT = GS_DATA-HKONT BINARY SEARCH .
    IF SY-SUBRC EQ 0 .
      L_TABIX = SY-TABIX.
      INSERT GS_DATA INTO GT_DATA INDEX L_TABIX .
      DELETE GT_QC INDEX QC_TABIX .
      CONTINUE.
    ELSE.
      READ TABLE GT_DATA  INTO GS_DATA_1 WITH KEY PSPID = GS_DATA-PSPID  BINARY SEARCH .
      IF SY-SUBRC EQ 0 .
        L_TABIX = SY-TABIX.
        INSERT GS_DATA INTO GT_DATA INDEX L_TABIX .
        DELETE GT_QC INDEX QC_TABIX.
        CONTINUE.
      ELSE.
        APPEND GS_DATA TO GT_DATA_HZ .  "先添加期初合计到 gt_data_hj
        CONTINUE.
      ENDIF.

    ENDIF.
  ENDLOOP.

  "追加GT_DATA行明细到 gt_data_hz.
  IF GT_DATA IS NOT INITIAL.
    APPEND LINES OF   GT_DATA TO GT_DATA_HZ .
  ENDIF.

*&--代码添加 BY HANDYBY 22.06.2017 16:21:58  BEGIN
  TYPES:BEGIN OF TY_ITEM2,
          BUKRS TYPE BUKRS,  "公司代码
          PSPID TYPE PS_PSPID, "项目定义
          XMMC  TYPE STRING,   "项目名称
          HKONT TYPE HKONT,     "科目
          KMMS  TYPE STRING,    "科目描述
          BELNR TYPE BELNR_D,    "会计凭证
          BUZEI TYPE BUZEI,     "凭证行号
          DMBTR TYPE DMBTR,    "本币码
          GJAHR TYPE GJAHR,   "会计年度
          BKTXT TYPE BKTXT,     "摘要
          JFJE  TYPE DMBTR,     "借方金额
          DFJE  TYPE DMBTR,     "贷方金额
          FX    TYPE STRING,    "方向
          WAERS TYPE WAERS,     "货币码
          YE    TYPE DMBTR,     "余额
          MATNR TYPE MATNR,     "物料号
          MAKTX TYPE MAKTX,     "物料描述
*&--代码添加 BY HANDYBY 20.06.2017 14:17:14  BEGIN
          MENGE TYPE BSEG-MENGE,  "数量
          MEINS TYPE BSEG-MEINS,  "单位
*&--代码添加 BY HANDYBY 20.06.2017 14:17:14  END
          SHKZG TYPE SHKZG,      "借贷标识
          XNEGP TYPE XNEGP,     "反记账
          XREF3 TYPE XREF3,     "参考码3
          BLART TYPE BLART,     "凭证类型
          BUDAT TYPE BUDAT,     "过账日期
          KUNNR TYPE KUNNR,      "客户
          KHMS  TYPE STRING,     "客户描述
          LIFNR TYPE LIFNR,     "供应商
          GYSMS TYPE STRING,   "供应商描述
          PROJK TYPE PS_PSP_PNR, "WBS
          ZUONR TYPE DZUONR,    "分配
          SEL,
*&--代码添加 BY HANDYBY 20.06.2017 10:28:51  BEGIN
          POSID TYPE PRPS-POSID,  "WBS外码
          POST1 TYPE PRPS-POST1,  "WBS描述
          STUFE TYPE PRPS-STUFE,  "WBS层级
*&--代码添加 BY HANDYBY 20.06.2017 10:28:51  END
        END OF TY_ITEM2 .
  DATA: LT_DATA_HZ TYPE TABLE OF TY_ITEM2,
        LS_DATA_HZ TYPE TY_ITEM2.

  MOVE-CORRESPONDING GT_DATA_HZ TO LT_DATA_HZ .
*&--代码添加 BY HANDYBY 22.06.2017 16:21:58  END


  "把期初、过账明细 按项目、科目维度汇总小计
*&--代码注释 BY HANDYBY 08.08.2017 20:25:59  BEGIN
*    LOOP AT  gt_data_hz INTO gs_data_hz .
*&--代码注释 BY HANDYBY 08.08.2017 20:25:59  END
*&--代码添加 BY HANDYBY 08.08.2017 20:25:16  BEGIN
  SORT GT_PROJ BY PSPID .
  LOOP AT  LT_DATA_HZ INTO LS_DATA_HZ .
*&--代码添加 BY HANDYBY 08.08.2017 20:25:16  END

    CLEAR:GS_DATA_SUM.
    MOVE-CORRESPONDING LS_DATA_HZ TO GS_DATA_SUM.
    AT NEW PSPID.
      CLEAR:XMMC.
      READ TABLE GT_PROJ INTO GS_PROJ WITH KEY PSPID = LS_DATA_HZ-PSPID BINARY SEARCH .
      IF SY-SUBRC EQ 0 .
        XMMC = GS_PROJ-POST1.
      ENDIF.
    ENDAT .
    "项目名称
    GS_DATA_SUM-XMMC = XMMC .
    "科目名称
    READ TABLE GT_SKAT INTO GS_SKAT WITH KEY SAKNR = GS_DATA_SUM-HKONT BINARY SEARCH .
    IF SY-SUBRC EQ 0 .
      GS_DATA_SUM-KMMS = GS_SKAT-TXT50 .
    ENDIF.

    APPEND  GS_DATA_SUM TO GT_DATA_SUM.

    DFXJ = DFXJ + GS_DATA_SUM-DFJE . "贷方小计
    JFXJ = JFXJ + GS_DATA_SUM-JFJE ."借方小计

    AT END OF  HKONT .
      CLEAR:GS_DATA_SUM .
      "新增一行按项目、科目汇总的小计一行
      GS_DATA_SUM-BUKRS = LS_DATA_HZ-BUKRS. "公司代码
      GS_DATA_SUM-PSPID = LS_DATA_HZ-PSPID. "项目号
      GS_DATA_SUM-XMMC = XMMC.   "项目名称
      GS_DATA_SUM-HKONT = LS_DATA_HZ-HKONT.  "科目
      "科目名称
      READ TABLE GT_SKAT INTO GS_SKAT WITH KEY SAKNR = GS_DATA_SUM-HKONT BINARY SEARCH .
      IF SY-SUBRC EQ 0 .
        GS_DATA_SUM-KMMS = GS_SKAT-TXT50 .
      ENDIF.
      GS_DATA_SUM-BKTXT = '小计'.          "摘要
      GS_DATA_SUM-WAERS = G_WAERS. "货币码
      GS_DATA_SUM-JFJE = JFXJ.  "借方合计
      GS_DATA_SUM-DFJE = DFXJ.  "贷方合计
      GS_DATA_SUM-YE =  GS_DATA_SUM-JFJE -  GS_DATA_SUM-DFJE .  "余额
      IF GS_DATA_SUM-YE > 0 .
        GS_DATA_SUM-FX = '借'.
      ELSEIF GS_DATA_SUM-YE < 0 .
        GS_DATA_SUM-FX = '贷'.
      ELSE.
        GS_DATA_SUM-FX = '平'.
      ENDIF.
      APPEND GS_DATA_SUM TO GT_DATA_SUM.

      "清除借方合计、贷方合计
      CLEAR:JFXJ,DFXJ.
    ENDAT .



  ENDLOOP.

*&--代码添加 BY HANDYBY 18.08.2017 11:26:25  BEGIN
  DATA: BEGIN OF LS_BSEG ,
          BUKRS TYPE BSEG-BUKRS,
          BELNR TYPE BSEG-BELNR,
          GJAHR TYPE BSEG-GJAHR,
          BUZEI TYPE BSEG-BUZEI,
          AUFNR TYPE BSEG-AUFNR,
          KOSTL TYPE BSEG-KOSTL,
          ZUONR TYPE BSEG-ZUONR,
        END OF LS_BSEG .
  DATA LT_BSEG LIKE TABLE OF LS_BSEG .
  DATA:BEGIN OF LS_AUFK ,
         AUFNR TYPE AUFK-AUFNR,
         KTEXT TYPE AUFK-KTEXT,
       END OF LS_AUFK .
  DATA LT_AUFK LIKE TABLE OF LS_AUFK .
  DATA: BEGIN OF LS_CSKT ,
          KOSTL TYPE CSKT-KOSTL,
          LTEXT TYPE CSKT-LTEXT,
        END OF LS_CSKT .
  DATA LT_CSKT LIKE TABLE OF LS_CSKT .

  SELECT BUKRS
         BELNR
         GJAHR
         BUZEI
         AUFNR
         KOSTL
         ZUONR
    INTO CORRESPONDING FIELDS OF TABLE LT_BSEG
    FROM BSEG
     FOR ALL ENTRIES IN GT_DATA_SUM
   WHERE BUKRS = GT_DATA_SUM-BUKRS
     AND BELNR = GT_DATA_SUM-BELNR
     AND GJAHR = GT_DATA_SUM-GJAHR
     AND BUZEI = GT_DATA_SUM-BUZEI .
  SORT LT_BSEG BY BUKRS BELNR GJAHR BUZEI .
  IF LT_BSEG IS NOT INITIAL .
    SELECT AUFNR
           KTEXT
      INTO CORRESPONDING FIELDS OF TABLE LT_AUFK
      FROM AUFK
       FOR ALL ENTRIES IN LT_BSEG
     WHERE AUFNR = LT_BSEG-AUFNR .
    SORT LT_AUFK BY AUFNR .

    SELECT KOSTL
           LTEXT
      INTO CORRESPONDING FIELDS OF TABLE LT_CSKT
      FROM CSKT
       FOR ALL ENTRIES IN LT_BSEG
     WHERE KOSTL = LT_BSEG-KOSTL
       AND SPRAS = SY-LANGU .
    SORT LT_CSKT BY KOSTL .
  ENDIF.

  LOOP AT GT_DATA_SUM INTO GS_DATA_SUM .
    READ TABLE LT_BSEG INTO LS_BSEG WITH KEY BUKRS = GS_DATA_SUM-BUKRS
                                             BELNR = GS_DATA_SUM-BELNR
                                             GJAHR = GS_DATA_SUM-GJAHR
                                             BUZEI = GS_DATA_SUM-BUZEI BINARY SEARCH .
    GS_DATA_SUM-AUFNR = LS_BSEG-AUFNR .
    GS_DATA_SUM-KOSTL = LS_BSEG-KOSTL .
    GS_DATA_SUM-ZUONR = LS_BSEG-ZUONR .
    READ TABLE LT_AUFK INTO LS_AUFK WITH KEY AUFNR = LS_BSEG-AUFNR BINARY SEARCH .
    GS_DATA_SUM-KTEXT = LS_AUFK-KTEXT .
    READ TABLE LT_CSKT INTO LS_CSKT WITH KEY KOSTL = LS_BSEG-KOSTL BINARY SEARCH .
    GS_DATA_SUM-LTEXT = LS_CSKT-LTEXT .

    MODIFY GT_DATA_SUM FROM GS_DATA_SUM .

    CLEAR LS_BSEG .
    CLEAR LS_AUFK .
    CLEAR LS_CSKT .
    CLEAR GS_DATA_SUM .
  ENDLOOP.
*&--代码添加 BY HANDYBY 18.08.2017 11:26:25  END

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_ALV_SHOW
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_ALV_SHOW .
  PERFORM INIT_LAYOUT.             "设置输出格式
  PERFORM INIT_SORT.               "设置排序、合计
  PERFORM INIT_VARIANT.            "设置变式控制
  PERFORM FRM_INIT_LVC.
  PERFORM FRM_EXCLUDE.
  GW_GRID_SETTINGS-EDT_CLL_CB = 'X'.
  PERFORM FRM_BUILD_EVENT.
  PERFORM FRM_OUTPUT TABLES GT_LVC              "输出
                            GT_SORT
                            GT_DATA_SUM
                     USING 'ALV_PF_STATUS'
                           'ALV_USER_COMMAND'
                           GW_LAYOUT
                           GW_VARIANT
                           GW_GRID_SETTINGS.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  INIT_LAYOUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM INIT_LAYOUT .
  GW_LAYOUT-ZEBRA        = 'X'.
  GW_LAYOUT-CWIDTH_OPT   = 'X'.
  GW_LAYOUT-BOX_FNAME = 'SEL'.
ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  INIT_SORT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM INIT_SORT .

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  INIT_VARIANT
*&---------------------------------------------------------------------*
FORM INIT_VARIANT .

ENDFORM.
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&      Form  FRM_INIT_LVC
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_INIT_LVC .
  INIT_FIELDCAT 'BUKRS'          '公司代码'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'PSPID'          '项目定义'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'XMMC'          '项目名称'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 20.06.2017 21:14:36  BEGIN
  INIT_FIELDCAT 'POSID'          'WBS'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'POST1'          'WBS描述'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'STUFE'          'WBS层级'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 20.06.2017 21:14:36  END
  INIT_FIELDCAT 'HKONT'          '科目'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'KMMS'          '科目描述'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'BELNR'          '会计凭证'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'BUZEI'          '凭证行号'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'GJAHR'          '会计年度'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'BKTXT'          '摘要'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'WAERS'          '货币码'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'JFJE'          '借方金额'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'DFJE'          '贷方金额'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'FX'          '方向'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'YE'          '余额'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'MATNR'          '物料号'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'MAKTX'          '物料描述'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 20.06.2017 21:15:49  BEGIN
  INIT_FIELDCAT 'MENGE'          '数量'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'MEINS'          '单位'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 20.06.2017 21:15:49  END
  INIT_FIELDCAT 'XREF3'          '参考码3'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'BLART'          '凭证类型'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'BUDAT'          '过账日期'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'KUNNR'          '客户'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'KHMS'          '客户描述'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'LIFNR'          '供应商'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'GYSMS'          '供应商描述'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'PROJK'          '凭证WBS'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'ZUONR'          '分配'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 18.08.2017 11:25:12  BEGIN
  INIT_FIELDCAT 'AUFNR'          '内部订单'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'KTEXT'          '内部订单描述'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'KOSTL'          '成本中心'             '' '' '' '' '' '' ''.
  INIT_FIELDCAT 'LTEXT'          '成本中心描述'             '' '' '' '' '' '' ''.
*&--代码添加 BY HANDYBY 18.08.2017 11:25:12  END

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_EXCLUDE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_EXCLUDE .

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_BUILD_EVENT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM FRM_BUILD_EVENT .

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  FRM_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_GT_LVC  text
*      -->P_GT_SORT  text
*      -->P_GT_DATA  text
*      -->P_0468   text
*      -->P_0469   text
*      -->P_GW_LAYOUT  text
*      -->P_GW_VARIANT  text
*      -->P_GW_GRID_SETTINGS  text
*----------------------------------------------------------------------*
FORM FRM_OUTPUT TABLES PT_LVC TYPE LVC_T_FCAT
                       PT_SORT TYPE LVC_T_SORT
                       PT_DATA
                USING PU_STATUS
                      PU_UCOMM
                      PW_LAYOUT TYPE LVC_S_LAYO
                      PW_VARIANT TYPE DISVARIANT
                      PW_GRID_SETTINGS TYPE LVC_S_GLAY.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY_LVC'
    EXPORTING
*     I_INTERFACE_CHECK        = ' '
*     I_BYPASSING_BUFFER       =
*     I_BUFFER_ACTIVE          =
      I_CALLBACK_PROGRAM       = SY-REPID
      I_CALLBACK_PF_STATUS_SET = PU_STATUS
      I_CALLBACK_USER_COMMAND  = PU_UCOMM
*     I_CALLBACK_TOP_OF_PAGE   = 'TOP-OF-PAGE'  "SEE FORM
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME         = ''
*     I_BACKGROUND_ID          = ' '
*     I_GRID_TITLE             =
      I_GRID_SETTINGS          = PW_GRID_SETTINGS
      IS_LAYOUT_LVC            = PW_LAYOUT
      IT_FIELDCAT_LVC          = PT_LVC[]
      IT_EXCLUDING             = GT_EXCLUDE
*     IT_SPECIAL_GROUPS_LVC    =
      IT_SORT_LVC              = PT_SORT[]
*     IT_FILTER_LVC            =
*     IT_HYPERLINK             =
*     IS_SEL_HIDE              =
*     I_DEFAULT                = 'X'
      I_SAVE                   = 'A'
      IS_VARIANT               = PW_VARIANT
      IT_EVENTS                = GT_EVENTS[]
*     IT_EVENT_EXIT            =
*     IS_PRINT_LVC             =
*     IS_REPREP_ID_LVC         =
*     I_SCREEN_START_COLUMN    = 0
*     I_SCREEN_START_LINE      = 0
*     I_SCREEN_END_COLUMN      = 0
*     I_SCREEN_END_LINE        = 0
*     I_HTML_HEIGHT_TOP        =
*     I_HTML_HEIGHT_END        =
*     IT_ALV_GRAPHICS          =
*     IT_EXCEPT_QINFO_LVC      =
*     IR_SALV_FULLSCREEN_ADAPTER        =
*    IMPORTING
*     E_EXIT_CAUSED_BY_CALLER  =
*     ES_EXIT_CAUSED_BY_USER   =
    TABLES
      T_OUTTAB                 = GT_DATA_SUM
    EXCEPTIONS
      PROGRAM_ERROR            = 1
      OTHERS                   = 2.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.                    " FRM_OUTPUT

FORM ALV_USER_COMMAND USING R_UCOMM LIKE SY-UCOMM
                            RS_SELFIELD TYPE SLIS_SELFIELD.

  DATA G_REF_GRID TYPE REF TO CL_GUI_ALV_GRID. "刷新行到内表


  CALL FUNCTION 'GET_GLOBALS_FROM_SLVC_FULLSCR'
    IMPORTING
      E_GRID = G_REF_GRID.

  CASE R_UCOMM.
* 双击
    WHEN '&IC1'.
*      READ TABLE GT_DATA INTO GS_DATA INDEX RS_SELFIELD-TABINDEX.
*      CHECK SY-SUBRC = 0.
*      IF RS_SELFIELD-FIELDNAME = 'BELNR'
*        AND GS_DATA-BELNR IS NOT INITIAL.
*        SET PARAMETER ID 'BLN' FIELD GS_DATA-BELNR.
*        SET PARAMETER ID 'BUK' FIELD GS_DATA-BUKRS.
*        SET PARAMETER ID 'GJR' FIELD GS_DATA-GJAHR.
*        CALL TRANSACTION 'FB03' AND SKIP FIRST SCREEN.
*      ENDIF.
*      IF RS_SELFIELD-FIELDNAME = 'VBELN'
*        AND GS_DATA-VBELN IS NOT INITIAL.
*        SET PARAMETER ID 'AUN' FIELD GS_DATA-VBELN.
*        CALL TRANSACTION 'VA03' AND SKIP FIRST SCREEN.
*      ENDIF.

  ENDCASE.

ENDFORM.                    "ALV_USER_COMMAND

FORM ALV_PF_STATUS USING RT_EXTAB TYPE SLIS_T_EXTAB.
  SET PF-STATUS 'STANDARD_FULLSCREEN' EXCLUDING RT_EXTAB.
ENDFORM.
