REPORT ZHRPA01.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1.


*关键日期筛选
IF G_G1 = 'X'.
  CALL TRANSACTION 'ZHRPA01_01'.
ENDIF.

*人事事件筛选
IF G_G2 = 'X'.
  CALL TRANSACTION 'ZHRPA01_02'.
ENDIF.
