
*&SPWIZARD: DECLARATION OF TABLECONTROL 'TAB_CONTR' ITSELF
CONTROLS: TAB_CONTR TYPE TABLEVIEW USING SCREEN 9001.

*&SPWIZARD: LINES OF TABLECONTROL 'TAB_CONTR'
DATA:     G_TAB_CONTR_LINES  LIKE SY-LOOPC.

DATA:     OK_CODE LIKE SY-UCOMM.
