FUNCTION ZMM002.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     VALUE(I_RSNUM) TYPE  RSNUM
*"  TABLES
*"      E_RESB STRUCTURE  ZMM002 OPTIONAL
*"----------------------------------------------------------------------

  DATA: BEGIN OF LS_RESB,
          RSNUM TYPE RESB-RSNUM,
          RSPOS TYPE RESB-RSPOS,
          RSART TYPE RESB-RSART,
          MATNR TYPE RESB-MATNR,
          BDMNG TYPE RESB-BDMNG,
          MEINS TYPE RESB-MEINS,
        END OF LS_RESB .
  DATA LT_RESB LIKE TABLE OF LS_RESB .
  DATA: BEGIN OF LS_MAKT,
          MATNR TYPE MAKT-MATNR,
          SPRAS TYPE MAKT-SPRAS,
          MAKTX TYPE MAKT-MAKTX,
        END OF LS_MAKT .
  DATA LT_MAKT LIKE TABLE OF LS_MAKT .

  SELECT RSNUM
         RSPOS
         RSART
         MATNR
         BDMNG
         MEINS
    INTO CORRESPONDING FIELDS OF TABLE LT_RESB
    FROM RESB
   WHERE RSNUM = I_RSNUM .
  IF LT_RESB IS NOT INITIAL .
    SELECT MATNR
           SPRAS
           MAKTX
      INTO CORRESPONDING FIELDS OF TABLE LT_MAKT
      FROM MAKT
       FOR ALL ENTRIES IN LT_RESB
     WHERE MATNR = LT_RESB-MATNR .
  ENDIF.

  LOOP AT LT_RESB INTO LS_RESB .
    MOVE-CORRESPONDING LS_RESB TO E_RESB .
    READ TABLE LT_MAKT INTO LS_MAKT WITH KEY MATNR = LS_RESB-MATNR .
    IF SY-SUBRC = 0 .
      E_RESB-MAKTX = LS_MAKT-MAKTX .
      CLEAR LS_MAKT .
    ENDIF.
    APPEND E_RESB .
    CLEAR LS_RESB .
  ENDLOOP.

ENDFUNCTION.
