*&---------------------------------------------------------------------*
*&  包含                ZMM045_SEL
*&---------------------------------------------------------------------*

* PO+SO
SELECTION-SCREEN BEGIN OF SCREEN 101 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001 .
PARAMETERS P_EKORG1 TYPE T024E-EKORG .
SELECT-OPTIONS S_LIFNR1 FOR LFA1-LIFNR .
SELECT-OPTIONS S_EBELN1 FOR EKKO-EBELN .
SELECT-OPTIONS S_BEDAT1 FOR EKKO-BEDAT .
SELECT-OPTIONS S_EKGRP1 FOR EKKO-EKGRP .
SELECT-OPTIONS S_ERNAM1 FOR EKKO-ERNAM .
SELECT-OPTIONS S_PSPNR1 FOR EKKN-PS_PSP_PNR .
SELECTION-SCREEN END OF BLOCK B1 .
SELECTION-SCREEN END OF SCREEN  101.

SELECTION-SCREEN BEGIN OF SCREEN 102 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002 .
PARAMETERS P_VKORG2 TYPE TVKO-VKORG .
SELECT-OPTIONS S_KUNNR2 FOR KNA1-KUNNR .
SELECT-OPTIONS S_VBELN2 FOR VBAK-VBELN .
SELECT-OPTIONS S_BSTNK2 FOR VBAK-BSTNK .
SELECT-OPTIONS S_ERNAM2 FOR VBAK-ERNAM .
SELECT-OPTIONS S_AUDAT2 FOR VBAK-AUDAT .
SELECTION-SCREEN END OF BLOCK B2 .
SELECTION-SCREEN END OF SCREEN  102.

* PO+PS
SELECTION-SCREEN BEGIN OF SCREEN 201 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-003 .
PARAMETERS P_EKORG3 TYPE T024E-EKORG .
SELECT-OPTIONS S_LIFNR3 FOR LFA1-LIFNR .
SELECT-OPTIONS S_EBELN3 FOR EKKO-EBELN .
SELECT-OPTIONS S_BEDAT3 FOR EKKO-BEDAT .
SELECT-OPTIONS S_EKGRP3 FOR EKKO-EKGRP .
SELECT-OPTIONS S_ERNAM3 FOR EKKO-ERNAM .
SELECT-OPTIONS S_PSPNR3 FOR EKKN-PS_PSP_PNR .
SELECTION-SCREEN END OF BLOCK B3 .
SELECTION-SCREEN END OF SCREEN 201.

SELECTION-SCREEN BEGIN OF SCREEN 202 AS SUBSCREEN .
SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-004 .
PARAMETERS P_BUKRS4 TYPE PRPS-PBUKR .
SELECT-OPTIONS S_KUNNR4 FOR PRPS-ZKHBM .
SELECT-OPTIONS S_POSID4 FOR PRPS-POSID .
SELECT-OPTIONS S_EBELN4 FOR PRPS-ZCGDDH .
SELECT-OPTIONS S_ERNAM4 FOR PRPS-ERNAM .
SELECT-OPTIONS S_ERDAT4 FOR PRPS-ERDAT .
SELECTION-SCREEN END OF BLOCK B4 .
SELECTION-SCREEN END OF SCREEN 202.
