
*&SPWIZARD: OUTPUT MODULE FOR TC 'TAB_CONTR'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TAB_CONTR_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE IT_ZMM002_1 LINES TAB_CONTR-lines.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TAB_CONTR'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GET LINES OF TABLECONTROL
MODULE TAB_CONTR_GET_LINES OUTPUT.
  G_TAB_CONTR_LINES = SY-LOOPC.
ENDMODULE.
