REPORT ZMM998.

DATA GT_MSEG TYPE TABLE OF MSEG.
DATA GS_MSEG TYPE MSEG.

DATA GT_PRPS TYPE TABLE OF PRPS.
DATA GS_PRPS TYPE PRPS.

SELECT * FROM MSEG
INTO CORRESPONDING FIELDS OF TABLE GT_MSEG
WHERE ZTEXT = ''
AND   MAT_PSPNR <> ''.

SELECT * FROM PRPS
 INTO CORRESPONDING FIELDS OF TABLE GT_PRPS
 FOR ALL ENTRIES IN GT_MSEG
 WHERE PSPNR = GT_MSEG-MAT_PSPNR.

LOOP AT GT_MSEG INTO GS_MSEG.

  READ TABLE GT_PRPS INTO GS_PRPS
  WITH KEY PSPNR = GS_MSEG-MAT_PSPNR.
  IF SY-SUBRC = 0.
    UPDATE MSEG SET ZTEXT  = GS_PRPS-POST1
     WHERE MBLNR  = GS_MSEG-MBLNR
     AND   MJAHR  = GS_MSEG-MJAHR
     AND   ZEILE  = GS_MSEG-ZEILE.
  ENDIF.

ENDLOOP.
