FUNCTION ZRFC_OA_SAP_002.
*"----------------------------------------------------------------------
*"*"本地接口：
*"  IMPORTING
*"     VALUE(DOCDATE) TYPE  CO_BLDAT
*"     VALUE(POSTGDATE) TYPE  CO_BUDAT
*"     VALUE(PERIOD) TYPE  CO_PERIO
*"     VALUE(DOC_HDR_TX) TYPE  CO_BLTXT
*"     VALUE(ZDYXTM) TYPE  CHAR30
*"     VALUE(ZBUKRS) TYPE  BUKRS
*"  TABLES
*"      GT_ZCO_DOC STRUCTURE  ZCO_DOC
*"      GT_RETURN STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------

  DATA GS_ZCO_DOC LIKE LINE OF GT_ZCO_DOC.
  DATA GS_RETURN  LIKE LINE OF GT_RETURN.


  DATA GS_DOC_HEADER TYPE BAPIDOCHDRU12P.

  DATA GT_DOC_ITEMS  TYPE TABLE OF BAPIRCITM.
  DATA GS_DOC_ITEMS  TYPE BAPIRCITM.

*记录日志数据
  DATA GT_ZZACKNOW TYPE TABLE OF ZZACKNOW.
  DATA GS_ZZACKNOW TYPE ZZACKNOW.

  GS_DOC_HEADER-CO_AREA    = '1000'.

  GS_DOC_HEADER-DOCDATE    = DOCDATE.

  GS_DOC_HEADER-POSTGDATE  = POSTGDATE.

  GS_DOC_HEADER-DOC_HDR_TX = DOC_HDR_TX.

  GS_DOC_HEADER-USERNAME   = SY-UNAME.

  LOOP AT GT_ZCO_DOC INTO GS_ZCO_DOC.
    GS_DOC_ITEMS-SEND_CCTR   = GS_ZCO_DOC-SEND_CCTR. "旧成本中心
    GS_DOC_ITEMS-SEN_WBS_EL = GS_ZCO_DOC-SEN_WBS_EL."WBS元素号（旧）
    GS_DOC_ITEMS-COST_ELEM  = GS_ZCO_DOC-COST_ELEM. "成本要素
    GS_DOC_ITEMS-VALUE_TCUR = GS_ZCO_DOC-VALUE_TCUR."金额
    GS_DOC_ITEMS-REC_ORDER  = GS_ZCO_DOC-REC_ORDER. "订单号（新）
    GS_DOC_ITEMS-TRANS_CURR = GS_ZCO_DOC-TRANS_CURR."货币
    GS_DOC_ITEMS-REC_CCTR   = GS_ZCO_DOC-REC_CCTR.  "新成本中心
    GS_DOC_ITEMS-SEN_ORDER  = GS_ZCO_DOC-SEN_ORDER. "订单号(旧)
    GS_DOC_ITEMS-REC_WBS_EL = GS_ZCO_DOC-REC_WBS_EL."WBS元素号（新）
    APPEND GS_DOC_ITEMS TO GT_DOC_ITEMS.
    CLEAR GS_DOC_ITEMS.
  ENDLOOP.

  CALL FUNCTION 'BAPI_ACC_PRIMARY_COSTS_POST'
    EXPORTING
      DOC_HEADER = GS_DOC_HEADER
*     IGNORE_WARNINGS       = ' '
* IMPORTING
*     DOC_NO     =
    TABLES
      DOC_ITEMS  = GT_DOC_ITEMS
      RETURN     = GT_RETURN
*     SEND_CRITERIA         =
*     REC_CRITERIA          =
*     CUSTOMER_FIELDS       =
    .

  CLEAR GS_ZZACKNOW.
  REFRESH GT_ZZACKNOW.

  READ TABLE GT_RETURN INTO GS_RETURN
  WITH KEY TYPE = 'E'.
  IF SY-SUBRC <> 0.
    GS_ZZACKNOW-ZZPROFG = 'S'.
    GS_ZZACKNOW-ZZCOMEN = GT_RETURN-MESSAGE.
    COMMIT WORK AND WAIT.
  ELSE.
    GS_ZZACKNOW-ZZPROFG = 'E'.
    GS_ZZACKNOW-ZZCOMEN = GS_RETURN-MESSAGE.
    ROLLBACK WORK.
  ENDIF.
   GS_ZZACKNOW-ZZDYXTM  = ZDYXTM.     "调用系统名
   GS_ZZACKNOW-ZZINTTY  = 'CODC'.     "接口类型
   GS_ZZACKNOW-ZZCDATE  = SY-DATUM.   "日期
   GS_ZZACKNOW-ZZCTIME  = SY-UZEIT.   "时间
   GS_ZZACKNOW-ZBUKRS   = ZBUKRS.    "公司代码
   GS_ZZACKNOW-USNAM    = SY-UNAME .   "用户名


  APPEND GS_ZZACKNOW TO GT_ZZACKNOW.
  MODIFY ZZACKNOW FROM TABLE GT_ZZACKNOW.


ENDFUNCTION.
