*----------------------------------------------------------------------*
***INCLUDE ZSET_ADD_ITEM.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Module  ZSET_ADD_ITEM  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE ZSET_ADD_ITEM OUTPUT.
  TYPES:BEGIN OF TY_MARA,
      MATNR TYPE MARA-MATNR,
      LAENG TYPE MARA-LAENG,
      BREIT TYPE MARA-BREIT,
      HOEHE TYPE MARA-HOEHE,
     END OF TY_MARA.

  DATA:IT_MARA TYPE TABLE OF TY_MARA.
  DATA:IS_MARA TYPE TY_MARA.
  DATA:ZSD10 TYPE CHAR30.

SELECT * FROM mara into CORRESPONDING FIELDS OF TABLE IT_MARA WHERE MARA~MATNR = XVBAP-MATNR.

IF XVBAP-ZSD0101 IS INITIAL.
  LOOP AT IT_MARA INTO IS_MARA.
   VBAP-ZSD0101 = IS_MARA-BREIT.
   VBAP-ZSD0102 = IS_MARA-HOEHE.
  ENDLOOP.
ENDIF.

LOOP AT SCREEN.
  IF SY-tCODE = 'VA03' OR SY-tCODE = 'VA23' OR SY-tCODE = 'VA13'.
    IF SCREEN-NAME = 'VBAP-ZSD0101'  OR SCREEN-NAME = 'VBAP-ZSD0102' OR SCREEN-NAME = 'VBAP-ZSD0103' OR SCREEN-NAME = 'VBAP-ZSD0103'
      OR SCREEN-NAME = 'VBAP-ZSD0104' OR SCREEN-NAME = 'VBAP-ZSD0105' OR SCREEN-NAME = 'VBAP-ZSD0106'
      OR SCREEN-NAME = 'VBAP-ZSD0107' OR SCREEN-NAME = 'VBAP-ZSD0108' OR SCREEN-NAME = 'VBAP-ZSD0109' OR SCREEN-NAME = 'VBAP-ZSD0110'.
        SCREEN-INPUT = 0.
        MODIFY SCREEN .
    ENDIF.
  ENDIF.
  AUTHORITY-CHECK OBJECT 'Z_SD_PRICE' ID 'ZPRICE' FIELD 'X'.
  IF sy-subrc <> 0."不等于0就表示没有权限，下面会屏蔽金额
    IF SCREEN-NAME = 'VBAP-ZSD0101'  OR SCREEN-NAME = 'VBAP-ZSD0102' OR SCREEN-NAME = 'VBAP-ZSD0103' OR SCREEN-NAME = 'VBAP-ZSD0103'
      OR SCREEN-NAME = 'VBAP-ZSD0104' OR SCREEN-NAME = 'VBAP-ZSD0105' OR SCREEN-NAME = 'VBAP-ZSD0106'
      OR SCREEN-NAME = 'VBAP-ZSD0107' OR SCREEN-NAME = 'VBAP-ZSD0108' OR SCREEN-NAME = 'VBAP-ZSD0109' OR SCREEN-NAME = 'VBAP-ZSD0110'.
        SCREEN-INPUT = 0.
        MODIFY SCREEN .
    ENDIF.
  ENDIF.
ENDLOOP.


  IF VBAP-ZSD0110  IS NOT INITIAL.
    SELECT SINGLE ZSD002
         FROM ZSD001
         INTO ZSD10
         WHERE ZSD001 = VBAP-ZSD0110.
  ENDIF.





ENDMODULE.
