REPORT ZTDTZ.
PARAMETERS:G_G1 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G2 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G3 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G4 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G5 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G6 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G7 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G8 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G9 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G10 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G11 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G12 TYPE CHAR1 RADIOBUTTON GROUP G1,
           G_G13 TYPE CHAR1 RADIOBUTTON GROUP G1.

"采购申请替代台账维护
IF G_G1 = 'X'.
 AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '01'.
  IF SY-SUBRC EQ 0 .
     CALL TRANSACTION 'ZTDPR01'.
   ELSE.
     MESSAGE '无权限查询ZTDTZQX的事务' TYPE 'S' DISPLAY LIKE 'E'.
   ENDIF.

ENDIF.

*采购订单替代台账维护
IF G_G2 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '02'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZTDPO01'.

      ELSE.

       MESSAGE '无权限查询ZTDPO01的事务' TYPE 'S' DISPLAY LIKE 'E'.

    ENDIF.
ENDIF.

*调拨替代台账维护
IF G_G3 = 'X'.
  AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '01'.
   IF SY-SUBRC EQ 0 .
       CALL TRANSACTION 'ZTDDB01'.
    ELSE.
       MESSAGE '无权限查询ZTDDB01的事务' TYPE 'S' DISPLAY LIKE 'E'.
    ENDIF.
ENDIF.

*出库替代台账维护
IF G_G4 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '01'.
     IF SY-SUBRC EQ 0 .
         CALL TRANSACTION 'ZTDCK01'.
      ELSE.
         MESSAGE '无权限查询ZTDCK01的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.


*采购申请替代关系查询
IF G_G5 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '03'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZTDPR02'.
     ELSE.
         MESSAGE '无权限查询ZTDPR02的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.

*采购订单替代关系查询
IF G_G6 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '03'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZTDPO02'.
     ELSE.

       MESSAGE '无权限查询ZTDPO02的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.


*调拨替代关系查询
IF G_G7 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '03'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZTDDB02'.
      ELSE.
         MESSAGE '无权限查询ZTDDB02的事务' TYPE 'S' DISPLAY LIKE 'E'.

   ENDIF.

ENDIF.

*出库替代关系查询
IF G_G8 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '03'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZTDCK02'.
      ELSE.
         MESSAGE '无权限查询ZTDCK02的事务' TYPE 'S' DISPLAY LIKE 'E'.
    ENDIF.

ENDIF.

*预算与累计申购数据对比报表
IF G_G9 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '04'.
     IF SY-SUBRC EQ 0 .
         CALL TRANSACTION 'ZMM021N'.
      ELSE.
         MESSAGE '无权限查询ZMM021N的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.

*采购申请导出审批列表
IF G_G10 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '04'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZMM022N'.
    ELSE.
       MESSAGE '无权限查询ZMM022N的事务' TYPE 'S' DISPLAY LIKE 'E'.
     ENDIF.
ENDIF.

*项目产值信息表
IF G_G11 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '05'.
     IF SY-SUBRC EQ 0 .
        CALL TRANSACTION 'ZPS001N'.
      ELSE.
          MESSAGE '无权限查询ZPS001N的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.

*项目物资预算与实际对比表
IF G_G12 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '06'.
     IF SY-SUBRC EQ 0 .
       CALL TRANSACTION 'ZPS010N'.
      ELSE.
       MESSAGE '无权限查询ZPS010N的事务' TYPE 'S' DISPLAY LIKE 'E'.
      ENDIF.
ENDIF.

*项目产值明细表
IF G_G13 = 'X'.
   AUTHORITY-CHECK OBJECT 'ZTDTZQX' ID 'ZTDTZCX' FIELD '05'.
     IF SY-SUBRC EQ 0 .
         CALL TRANSACTION 'ZPS011N'.
       ELSE.
          MESSAGE '无权限查询ZPS011N的事务' TYPE 'S' DISPLAY LIKE 'E'.
     ENDIF.
ENDIF.
