*&---------------------------------------------------------------------*
*&  包含                ZXCN1U11
*&---------------------------------------------------------------------*
"break  it02.
*DATA: M TYPE I .
*SAP_PROJ_IMP-ZLG = 'lougao'.
"GINCLUDE_PROJ
CONDENSE GINCLUDE_PROJ-ZSJS NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZJSFZR NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZCBYSZY NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZZLY NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZAQY NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZSGY NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZCGY NO-GAPS.
CONDENSE GINCLUDE_PROJ-ZCGZY NO-GAPS.
"到此日期前5天开始到此日期为止，消息提示：注意！履约保函结束日期将在ZLYBHJSSJ到期
IF SAP_PROJ_IMP-ZLYBHJSSJ IS NOT INITIAL.
   IF SAP_PROJ_IMP-ZLYBHJSSJ - SY-DATUM <= 5 AND SAP_PROJ_IMP-ZLYBHJSSJ - SY-DATUM > 0.
      CONCATENATE '注意！履约保函结束日期将在'  SAP_PROJ_IMP-ZLYBHJSSJ '到期' INTO SAP_PROJ_IMP-ZLYBHJSSJ_TX.
    ENDIF.
ENDIF.
"到此日期前5天开始到此日期为止，消息提示：注意！预付款保函结束日期将在ZYFKBHJSSJ到期ZYFKBHJSSJ

IF SAP_PROJ_IMP-ZYFKBHJSSJ IS NOT INITIAL.
  IF SAP_PROJ_IMP-ZYFKBHJSSJ - SY-DATUM <= 5 AND SAP_PROJ_IMP-ZYFKBHJSSJ - SY-DATUM > 0.
      CONCATENATE '注意！预付款保函结束日期将在'  SAP_PROJ_IMP-ZYFKBHJSSJ '到期' INTO SAP_PROJ_IMP-ZYFKBHJSSJ_TX.
    ENDIF.
ENDIF.

"到此日期前5天开始到此日期为止，消息提示：注意！质保结束日期将在ZZBJSSJ到期
IF SAP_PROJ_IMP-ZZBJSSJ IS NOT INITIAL.
  IF SAP_PROJ_IMP-ZZBJSSJ - SY-DATUM <= 5 AND SAP_PROJ_IMP-ZZBJSSJ - SY-DATUM > 0.
      CONCATENATE '注意！质保结束日期将在'  SAP_PROJ_IMP-ZZBJSSJ '到期' INTO SAP_PROJ_IMP-ZZBJSSJ_TX.
    ENDIF.
ENDIF.

"到此日期前5天开始到此日期为止，消息提示：注意！外经证开始日期将在ZWZJKSSJ到期
IF SAP_PROJ_IMP-ZWZJKSSJ IS NOT INITIAL.
  IF SAP_PROJ_IMP-ZWZJKSSJ - SY-DATUM <= 5 AND SAP_PROJ_IMP-ZWZJKSSJ - SY-DATUM > 0.
      CONCATENATE '注意！外经证开始日期将在'  SAP_PROJ_IMP-ZWZJKSSJ '到期' INTO SAP_PROJ_IMP-ZWZJKSSJ_TX.
    ENDIF.
ENDIF.

"到此日期前5天开始到此日期为止，消息提示：注意！外经证结束日期将在ZWZJJSSJ到期
IF SAP_PROJ_IMP-ZWZJJSSJ IS NOT INITIAL.
  IF SAP_PROJ_IMP-ZWZJJSSJ - SY-DATUM <= 5 AND SAP_PROJ_IMP-ZWZJJSSJ - SY-DATUM > 0.
      CONCATENATE '注意！外经证结束日期将在'  SAP_PROJ_IMP-ZWZJJSSJ '到期' INTO SAP_PROJ_IMP-ZWZJJSSJ_TX.
    ENDIF.
ENDIF.

"客户名称查询
IF SAP_PROJ_IMP-ZKHBM NE ''.
  SELECT SINGLE NAME1 INTO GIN_ZKHBMNAME FROM KNA1 WHERE KUNNR = SAP_PROJ_IMP-ZKHBM .
ENDIF.
MOVE-CORRESPONDING  SAP_PROJ_IMP TO GINCLUDE_PROJ.
* M  =  2.
